SENA/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('carsapp/', include('carsapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carsapp/urls.py
from django.urls import path
from . import views

app_name = 'carsapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('inicio/', views.inicio, name='inicio'),
    path('shopping/', views.shopping, name='shopping'),

    path('usuarioCrear/<int:id>/', views.usuarioCrear, name='usuarioCrear'),
    path('usuarioGuardar', views.usuarioGuardar, name='usuarioGuardar'),
    path('usuarioListar/', views.UsuarioLista.as_view(), name='usuarioListar'), 
    path('usuarioEliminar/<int:id>/', views.usuarioEliminar, name='usuarioEliminar'),
    path('usuarioFormActualizar/<int:id>/', views.usuarioFormActualizar, name='usuarioFormActualizar'),
    path('usuarioActualizar', views.usuarioActualizar, name='usuarioActualizar'),

    path('empleadoListar/', views.EmpleadoLista.as_view(), name='empleadoListar'), 
    path('empleadoFormulario/', views.empleadoFormulario, name='empleadoFormulario'),
    path('empleadoGuardar/', views.empleadoGuardar, name='empleadoGuardar'),
    path('empleadoEliminar/<int:id>/', views.empleadoEliminar, name='empleadoEliminar'),
    path('empleadoFormActualizar/<int:id>/', views.empleadoFormActualizar, name='empleadoFormActualizar'),
    path('empleadoActualizar', views.empleadoActualizar, name='empleadoActualizar'),
    
    path('clienteListar/', views.ClienteLista.as_view(), name='clienteListar'), 
    path('clienteFormulario/', views.clienteFormulario, name='clienteFormulario'),
    path('clienteGuardar/', views.clienteGuardar, name='clienteGuardar'),
    path('clienteEliminar/<int:id>/', views.clienteEliminar, name='clienteEliminar'),
    path('clienteFormActualizar/<int:id>/', views.clienteFormActualizar, name='clienteFormActualizar'),
    path('clienteActualizar', views.clienteActualizar, name='clienteActualizar'),

    path('vehiculoListar/', views.VehiculoLista.as_view(), name='vehiculoListar'),
    path('vehiculoFormulario/<int:id>/', views.vehiculoFormulario, name='vehiculoFormulario'),
    path('vehiculoGuardar/', views.vehiculoGuardar, name='vehiculoGuardar'),
    path('vehiculoEliminar/<int:id>/', views.vehiculoEliminar, name='vehiculoEliminar'),
    path('vehiculoFormActualizar/<int:id>/', views.vehiculoFormActualizar, name='vehiculoFormActualizar'),
    path('vehiculoActualizar', views.vehiculoActualizar, name='vehiculoActualizar'),

    path('servicioListar/', views.ServicioLista.as_view(), name='servicioListar'),
    path('servicioFormulario/', views.servicioFormulario, name='servicioFormulario'),
    path('servicioGuardar/', views.servicioGuardar, name='servicioGuardar'),
    path('servicioEliminar/<int:id>/', views.servicioEliminar, name='servicioEliminar'),
    path('servicioFormActualizar/<int:id>/', views.servicioFormActualizar, name='servicioFormActualizar'),
    path('servicioActualizar', views.servicioActualizar, name='servicioActualizar'),

    path('proveedorListar/', views.ProveedorLista.as_view(), name='proveedorListar'), 
    path('proveedorFormulario/', views.proveedorFormulario, name='proveedorFormulario'),
    path('proveedorGuardar/', views.proveedorGuardar, name='proveedorGuardar'),
    path('proveedorEliminar/<int:id>/', views.proveedorEliminar, name='proveedorEliminar'),
    path('proveedorFormActualizar/<int:id>/', views.proveedorFormActualizar, name='proveedorFormActualizar'),
    path('proveedorActualizar', views.proveedorActualizar, name='proveedorActualizar'),

    path('inventarioListar/', views.InventarioLista.as_view(), name='inventarioListar'),
    path('inventarioFormulario/', views.inventarioFormulario, name='inventarioFormulario'),
    path('inventarioGuardar/', views.inventarioGuardar, name='inventarioGuardar'),
    path('inventarioEliminar/<int:id>/', views.inventarioEliminar, name='inventarioEliminar'),
    path('inventarioFormActualizar/<int:id>/', views.inventarioFormActualizar, name='inventarioFormActualizar'),
    path('inventarioActualizar', views.inventarioActualizar, name='inventarioActualizar'),

    path('crearRevision/<int:id>/', views.crearRevision, name='crearRevision'),
    path('RevisionVehiLista/', views.RevisionVehiLista.as_view(), name='RevisionVehiLista'),
    path('revisionEliminar/<int:id>/', views.revisionEliminar, name='revisionEliminar'),
    path('asignarEmpleadoRevision/<int:id>/', views.asignarEmpleadoRevision, name='asignarEmpleadoRevision'),
    path('AgregarServicioLista/<int:id>/', views.AgregarServicioLista, name='AgregarServicioLista'),
    path('agregarServicioAVehiculo/<int:id>/', views.agregarServicioAVehiculo, name='agregarServicioAVehiculo'),
    path('quitarServicioDeStage/<int:id>/', views.quitarServicioDeStage, name='quitarServicioDeStage'),

    path('MantenimientoVehiLista/', views.MantenimientoVehiLista.as_view(), name='MantenimientoVehiLista'),
    path('crearMantenimiento/<int:id>/', views.crearMantenimiento, name='crearMantenimiento'),
    path('mantenimientoEliminar/<int:id>/', views.mantenimientoEliminar, name='mantenimientoEliminar'),
    path('mantenimientoDetalles/<int:id>/', views.mantenimientoDetalles, name='mantenimientoDetalles'),
    path('mantenimientoServicioEliminar/<int:id>/', views.mantenimientoServicioEliminar, name='mantenimientoServicioEliminar'),
    path('agregarOtroServiList/<int:id>/', views.agregarOtroServiList, name='agregarOtroServiList'),
    path('agregarOtroServiAVehi/<int:id>/', views.agregarOtroServiAVehi, name='agregarOtroServiAVehi'),
    path('vaciarSessionServis/<int:id>/', views.vaciarSessionServis, name='vaciarSessionServis'),

    path('FacturasLista/', views.FacturasLista.as_view(), name='FacturasLista'),
    path('crearFacturaServicios/<int:id>/', views.crearFacturaServicios, name='crearFacturaServicios'),
    path('facturasDetalles/<int:id>/', views.facturasDetalles, name='facturasDetalles'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    #rutas carrito
    path('vender/', views.vender, name='vender'),
    path('agregar_carrito/<str:id>/', views.agregarCarrito, name='agregar_carrito'),
    path('ver_carrito/', views.verCarrito, name='ver_carrito'),
    path('quitar_producto/<str:id>/', views.quitarProducto, name='quitar_producto'),
    path('limpiar_carrito/', views.limpiarCarrito, name='limpiar_carrito'),
    path('editar_carrito/<str:id>/<int:cantidad>/', views.editarCarrito, name='editar_carrito'),

    path('guardar_pedido/', views.guardarPedido, name='guardar_pedido'),
]

carsapp/views.py
from django.contrib.messages.api import error
from django.core.checks import messages
from django.db.models import query
from django.db.models.aggregates import Count

from django.shortcuts import redirect, render
from django.views.generic import ListView
from django.db import transaction

from django.forms.models import model_to_dict

from datetime import datetime

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.db import IntegrityError
from django.contrib import messages

from .models import *

"""
def handle_uploaded_file(f):
    from django.conf import settings
    from django.core.files.storage import default_storage
    print("Archivo", f)
    print("Ruta: ",settings.MEDIA_ROOT)
    #save_path = os.path.join(settings.MEDIA_ROOT, 'gep/', f)
    save_path = '{0}/{1}'.format('productos', f)
    print(save_path)
    
    path = default_storage.save(save_path, f)
    if path:
        print("ok")
    else:
        print("error")
    return f

def createProducto(request):
    if request.method == 'POST':
        try:
            with transaction.atomic():
                nombre = request.POST['nombre']
                estado = True if (request.POST["estado"] == 'true') else False
                precio = request.POST['precio']
                categoria = request.POST['categoria']
                descripcion = request.POST['descripcion']
                f = handle_uploaded_file(request.FILES['file'])
                f = 'media/productos/' + str(f)
                print(f)
                producto = Producto(nombre_prod = nombre, precio = precio ,estado_prod = estado, categoria = Categoria.objects.get(pk = categoria), imge = f, descripcion = descripcion)
                producto.save()
        except IntegrityError:
            print("error")        
        return HttpResponseRedirect(reverse('laNegra:showProducto', args=() ))
    else :
        return HttpResponse("nada")  

"""

def login(request):
    try:
        q = Usuario.objects.get(usuario = request.POST['usuario'], clave = request.POST['clave'])
        q2 = Empleados.objects.get(cedula_Emp = request.POST['usuario'])
        request.session["login"] = [q2.nombre_Emp, q2.apellido_Emp, q.rol, q.usuario, q.id]
        return HttpResponseRedirect(reverse('carsapp:inicio', args=() ))
    except Usuario.DoesNotExist:
        #return HttpResponse("Usuario o Clave no existe...!")
        return HttpResponseRedirect(reverse('carsapp:index', args=() ))
    

def logout(request):
    try:
        del request.session["login"]
        return HttpResponseRedirect(reverse('carsapp:index', args=() ))
    except:
        return HttpResponse("No se pudo cerrar sesión, intente de nuevo...")

def inicio(request):
    return render(request, 'carsapp/inicio.html')

def index(request):
    return render( request, 'carsapp/index.html')

def shopping(request):
    return render( request, "carsapp/shopping.html")



#Servicio
class ServicioLista(ListView):
    template_name = 'carsapp/servicioListar.html'
    queryset = Servicios.objects.all()
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Lista de Empleados'

        print(context)

        return context

def servicioFormulario(request):
    return render(request, "carsapp/servicio_Crear.html")

def servicioGuardar(request):
    if request.method == 'POST':

        q = Servicios(
            tipo_Servicio = request.POST['tipo_Servicio'],
            nombre_Servicio = request.POST['nombre_Servicio'],
            valor_Servicio = request.POST['valor_Servicio'],
        )
    q.save()
    messages.success(request, 'Servicio Creado correctamente..!')
    return HttpResponseRedirect(reverse('carsapp:servicioListar', args=() ))

def servicioEliminar(request, id):
    try:
        q = Servicios.objects.get(pk = id)
        q.delete()
        messages.success(request, 'Servicio eliminado correctamente..!')
    except Servicios.DoesNotExist:
        messages.error(request, "No existe el Servicio " + str(id))
    except IntegrityError:
        messages.error(request, "No puede eliminar este Servicio porque existen registros.")
    except:
        messages.error(request, "Ocurrió un error")
        
    return HttpResponseRedirect(reverse('carsapp:servicioListar', args=() ))

def servicioFormActualizar(request, id):
    q = Servicios.objects.get(pk = id)
    contexto = { "dato": q }
    return render(request, 'carsapp/servicioFormActualizar.html', contexto)

def servicioActualizar(request):
    q = Servicios.objects.get(pk = request.POST['id'])

    q.tipo_Servicio = request.POST['tipo_Servicio']
    q.nombre_Servicio = request.POST['nombre_Servicio']
    q.valor_Servicio = request.POST['valor_Servicio']
    
    q.save()
    messages.success(request, 'Servicio actualizado correctamente..!')
    return HttpResponseRedirect(reverse('carsapp:servicioListar', args=() ))

#Inventario
class InventarioLista(ListView):
    template_name = 'carsapp/inventarioListar.html'
    queryset = Inventario.objects.all()
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Lista de Empleados'

        print(context)

        return context

def inventarioFormulario(request):
    proveedor = Proveedor.objects.all()
    contexto = {'proveedor': proveedor}
    return render(request, "carsapp/inventario_Crear.html", contexto)

def inventarioGuardar(request):
    if request.method == 'POST':
        proveedor = Proveedor.objects.get(pk = request.POST['proveedor'])

        q = Inventario(
            Ref = request.POST['Ref'],
            producto = request.POST['producto'],
            imagen = request.FILES['imagen'],
            provedor = proveedor,
            stock = request.POST['stock'],
            valor_Proveedor = request.POST['valor_Proveedor'],
            valor_Venta = request.POST['valor_Venta'],
        )
    q.save()
    messages.success(request, 'Producto Creado correctamente..!')
    return HttpResponseRedirect(reverse('carsapp:inventarioListar', args=() ))

def inventarioEliminar(request, id):
    try:
        q = Inventario.objects.get(pk = id)
        q.delete()
        messages.success(request, 'Producto eliminado correctamente..!')
    except Servicios.DoesNotExist:
        messages.error(request, "No existe el Producto " + str(id))
    except IntegrityError:
        messages.error(request, "No puede eliminar este Producto porque existen registros.")
    except:
        messages.error(request, "Ocurrió un error")
        
    return HttpResponseRedirect(reverse('carsapp:inventarioListar', args=() ))

def inventarioFormActualizar(request, id):
    proveedor = Proveedor.objects.all()
    q = Inventario.objects.get(pk = id)
    contexto = { "dato": q, 'proveedor': proveedor}
    
    return render(request, 'carsapp/inventarioFormActualizar.html', contexto)

def inventarioActualizar(request):
    q = Inventario.objects.get(pk = request.POST['id'])
    proveedor = Proveedor.objects.get(pk = request.POST['proveedor'])

    try:
        q.Ref = request.POST['Ref']
        q.producto = request.POST['producto']
        q.imagen = request.FILES['imagen']
        q.provedor = proveedor
        q.stock = request.POST['stock']
        q.valor_Proveedor = request.POST['valor_Proveedor']
        q.valor_Venta = request.POST['valor_Venta']

        q.save()
        messages.success(request, 'Producto actualizado correctamente..!')
        return HttpResponseRedirect(reverse('carsapp:inventarioListar', args=() ))
    except proveedor.DoesNotExist:
        messages.error(request, "Seleccione el proveedor ")

#Lista_CLiente
class ClienteLista(ListView):
    template_name = 'carsapp/clienteListar.html'
    queryset = Lista_Cliente.objects.all()
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Lista de Empleados'

        print(context)

        return context

def clienteFormulario(request):
    return render(request, "carsapp/cliente_Crear.html")

def clienteGuardar(request):
    if request.method == 'POST':

        q = Lista_Cliente(
            id_Cliente = request.POST['id_Cliente'],
            tipo_Documento = request.POST['tipo_Documento'],
            tipo_Cliente = request.POST['tipo_Cliente'],
            nombre_Cliente = request.POST['nombre_Cliente'],
            apellido_Cliente = request.POST['apellido_Cliente'],
            email_Cliente = request.POST['email_Cliente'],
            telefono_Cliente = request.POST['telefono_Cliente'],
        )
    q.save()
    messages.success(request, 'Cliente Creado correctamente..!')
    return HttpResponseRedirect(reverse('carsapp:clienteListar', args=() ))

def clienteEliminar(request, id):
    try:
        q = Lista_Cliente.objects.get(pk = id)
        q.delete()
        messages.success(request, 'Cliente eliminado correctamente..!')
    except Servicios.DoesNotExist:
        messages.error(request, "No existe el Cliente " + str(id))
    except IntegrityError:
        messages.error(request, "No puede eliminar este Cliente porque existen registros.")
    except:
        messages.error(request, "Ocurrió un error")
        
    return HttpResponseRedirect(reverse('carsapp:clienteListar', args=() ))

def clienteFormActualizar(request, id):
    q = Lista_Cliente.objects.get(pk = id)
    contexto = { "dato": q }
    return render(request, 'carsapp/clienteFormActualizar.html', contexto)

def clienteActualizar(request):
    q = Lista_Cliente.objects.get(pk = request.POST['id'])

    q.tipo_Documento = request.POST['tipo_Documento']
    q.tipo_Cliente = request.POST['tipo_Cliente']
    q.nombre_Cliente = request.POST['nombre_Cliente']
    q.apellido_Cliente = request.POST['apellido_Cliente']

carsapp/templates/carsapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CarsApp - {% block titulo %} App {% endblock %} </title>

    <!--Bootstrap-->
    
    <link rel="stylesheet" href="{% static 'carsapp/CSS/bootstrap.min.css' %}"/>

    <link rel="stylesheet" href="{% static 'carsapp/CSS/estilos.css' %}"/>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'carsapp/img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'carsapp/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="24x24" href="{% static 'carsapp/img/favicon-24x24.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'carsapp/img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'carsapp/img/site.webmanifest' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet">
</head>

<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg" id="navBar">
        <a class="navbar-brand" href="{% url 'carsapp:inicio' %}">CarsApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Administración
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.session.login.2 == 'Administrador'  or request.session.login.2 == 'Recepcionista' %}
                            <a class="dropdown-item" href="{% url 'carsapp:clienteListar' %}">Clientes</a>
                        {% endif %}
                        {% if request.session.login.2 == 'Administrador' %}
                            <a class="dropdown-item" href="{% url 'carsapp:empleadoListar' %}">Empleados</a>
                        {% endif %}
                        {% if request.session.login.2 == 'Administrador' %}
                            <a class="dropdown-item" href="{% url 'carsapp:usuarioListar' %}">Usuarios</a>
                        {% endif %}
                        {% if request.session.login.2 == 'Administrador' or request.session.login.2 == 'Empleado' %}
                            <a class="dropdown-item" href="{% url 'carsapp:servicioListar' %}">Servicios</a>
                        {% endif %}
                        {% if request.session.login.2 == 'Administrador' or request.session.login.2 == 'Recepcionista' %}
                            <a class="dropdown-item" href="{% url 'carsapp:vehiculoListar' %}">Vehículos</a>
                        {% endif %}                        
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Inventario
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.session.login.2 == 'Administrador' or request.session.login.2 == 'Empleado' %}
                            <a class="dropdown-item" href="{% url 'carsapp:inventarioListar' %}">Productos</a>
                        {% endif %}
                        {% if request.session.login.2 == 'Administrador' or request.session.login.2 == 'Recepcionista' %}
                            <a class="dropdown-item" href="{% url 'carsapp:proveedorListar' %}">Proveedores</a>
                        {% endif %}         
                    </div>
                </li>
                {% if request.session.login.2 == 'Administrador' or request.session.login.2 == 'Recepcionista' %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Facturación
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'carsapp:FacturasLista' %}">Facturas</a>
                            <a class="dropdown-item" href="{% url 'carsapp:vender' %}">Ventas</a>
                            <!--<a class="dropdown-item" href="{% url 'carsapp:shopping' %}">Shopping</a>-->
                            
                        </div>
                    </li>
                {% endif %}
                {% if request.session.login.2 == 'Administrador' or request.session.login.2 == 'Empleado' %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Procesos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'carsapp:RevisionVehiLista' %}">Revisión vehículo</a>
                            <a class="dropdown-item" href="{% url 'carsapp:MantenimientoVehiLista' %}">Mantenimiento vehículo</a>
                            <!--<a class="dropdown-item" href="">Estado del vehículo</a>-->
                        </div>
                    </li>
                {% endif %}
               
            </ul>
            <div>
                {% if request.session.login %}
                    <div class="bienvenida">
                        Bienvenido {{ request.session.login.0 }} {{ request.session.login.1 }} ({{ request.session.login.2 }})
                    </div>
                    <abbr title="Cerrar sesion"><a class="btn btn-outline-success my-2 my-sm-0" type="submit" id="btn-search" href="{% url 'carsapp:logout' %}"><i class="fas fa-sign-out-alt"></i></a></abbr>
                {% endif %}
            </div>
        </div>
    </nav>
    {% endblock %}
    <div id="respuesta_ajax"></div>
        {% block contenedor %} ... {% endblock %}
    </div>

    {% block footer %}
    <footer>
        <div class="footer">
            <p><a href="{% if request.session.login %}{% url 'carsapp:inicio' %}{% endif %}">CarsApp</a> ©2021 Todos los derechos reservados</p>
        </div>
    </footer>
    {% endblock %}

    <script src="{% static 'carsapp/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'carsapp/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'carsapp/js/libreria.js' %}"></script>
    <script src="https://kit.fontawesome.com/c6f6d15d46.js" crossorigin="anonymous"></script>
    <script src="{% static 'carsapp/js/app.js' %}"></script>
    <script src="{% static 'carsapp/js/api.json' %}"></script>
</body>

</html>

carsapp/templates/carsapp/vender_ver.html
{% extends 'carsapp/base.html' %}
{% load humanize %}
{% load static %}

{% block titulo %} Ventas {% endblock %}

{% block contenedor %}
<div class="card text-white bg-secondary">
    <div class="card-body">
        <div>
            Ver compra
        </div>
        <div class="btn-cerrarSesion">
            <a class="btn btn-primary" href="{% url 'carsapp:vender' %}" id="ID_BTNListar4">Volver</a>
        </div>
    </div>
</div>
<div>
    {% if messages %}
        {% for m in messages %}
        <div class="alert alert-{% if m.level == 25 %}success{% elif m.level == 40 %}danger{% else %}info{% endif %} alert-dismissible fade show" role="alert">
            {{ m }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    
    {% endif %}
</div>
<br>

{% if datos or request.session.carrito %}
    <h1>Cantidad de Productos: {{ request.session.bolsa }}</h1>
    <h1>Detalle:</h1>
    <table class="table  table-hover">
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Subtotal</th>
            <th>Acciones</th>
        </tr>
        {% for producto in datos %}
        <tr>
            <td><img src="{{ producto.foto.url }}" alt="{{ producto.producto }}" width="50"><br>{{ producto.nombre }}</td>
            <td><input type="number" value="{{ producto.cantidad }}" name="cantidad" size="3" oninput="editarCantidadCarrito(this.value, '{{ producto.producto }}', {{ producto.precio }}, '{{ forloop.counter }}', '{% url 'carsapp:editar_carrito' '0' 0 %}');" min="1"/></td>
            <td>$ {{ producto.precio|intcomma }}</td>
            <td id="cambio_subtotal_{{ producto.producto }}">
                $ {{ producto.subtotal|intcomma }}
            </td>
            <td>
                <input type="button" id="s_{{ forloop.counter }}" value="{{ producto.subtotal }}" style="display:none;"/>
                <abbr title="Eliminar"><a class="btn btn-danger" href="javascript:eliminarProductoCarrito('{% url 'carsapp:quitar_producto' producto.producto %}')" role="button"><i class="fas fa-trash-alt"></i></a></abbr>
            </td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <h1 class="display-4">Total: <span id="total_carrito">$ {{ total|intcomma }}</span></h1>
    <br><br>
    <form action="{% url 'carsapp:guardar_pedido' %}" method="POST" onsubmit="return guardarPedido()">
        {% csrf_token %}
        <div>
            <label style="color: blue; font-size: large; font-weight: 600;">Cliente:</label>
            <select name="cliente" class="form-control" required>
                <option value="0">Seleccione cliente</option>
                {% for i in clientes %}
                    <option value="{{ i.id_Cliente }}">{{ i.nombre_Cliente }} {{ i.apellido_Cliente }} ({{ i.id_Cliente }})</option>
                {% endfor %}
            </select>
        </div>
        <br>
        <button type="submit" class="btn btn-primary btn-lg">Facturar</button>
        <a href="{% url 'carsapp:limpiar_carrito' %}" type="button" class="btn btn-danger btn-lg">Limpiar Carrito</a>
    </form>
    <br/>
    

    {% else %}
    No hay datos aún.
    {% endif %}

{% endblock %}
    